# Generated by Django 5.2.17 on 2026-09-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_taskcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_project_fe19a5_idx',
            old_name='tasks_project_status_idx',
        ),
    ]
